In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
voc_size = 10000

In [4]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9016, 1599, 3589, 907],
 [9016, 1599, 3589, 1875],
 [9016, 6794, 3589, 4941],
 [8605, 8168, 9490, 1657, 7562],
 [8605, 8168, 9490, 1657, 3653],
 [4720, 9016, 4572, 3589, 7032],
 [2337, 2253, 6842, 1657]]

In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [6]:
sent_length = 8

In [7]:
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

In [8]:
print(embedded_docs)

[[   0    0    0    0 9016 1599 3589  907]
 [   0    0    0    0 9016 1599 3589 1875]
 [   0    0    0    0 9016 6794 3589 4941]
 [   0    0    0 8605 8168 9490 1657 7562]
 [   0    0    0 8605 8168 9490 1657 3653]
 [   0    0    0 4720 9016 4572 3589 7032]
 [   0    0    0    0 2337 2253 6842 1657]]


In [9]:
#features representation
dim = 10

In [10]:
model = Sequential(
    [Embedding(voc_size, dim, input_length=sent_length),
     ]
)

In [11]:
model.compile('adam', 'mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 316ms/step


array([[[-3.85287032e-02,  4.16574962e-02,  4.57687713e-02,
         -1.44444928e-02,  5.57371229e-03, -4.61345576e-02,
          4.33220156e-02, -3.06491852e-02, -2.05924045e-02,
          9.51985270e-03],
        [-3.85287032e-02,  4.16574962e-02,  4.57687713e-02,
         -1.44444928e-02,  5.57371229e-03, -4.61345576e-02,
          4.33220156e-02, -3.06491852e-02, -2.05924045e-02,
          9.51985270e-03],
        [-3.85287032e-02,  4.16574962e-02,  4.57687713e-02,
         -1.44444928e-02,  5.57371229e-03, -4.61345576e-02,
          4.33220156e-02, -3.06491852e-02, -2.05924045e-02,
          9.51985270e-03],
        [-3.85287032e-02,  4.16574962e-02,  4.57687713e-02,
         -1.44444928e-02,  5.57371229e-03, -4.61345576e-02,
          4.33220156e-02, -3.06491852e-02, -2.05924045e-02,
          9.51985270e-03],
        [-3.17734964e-02, -4.10644300e-02, -3.17892917e-02,
         -1.75112486e-02, -4.21899222e-02, -1.10825896e-02,
          4.53280546e-02, -2.25380659e-02,  2.541926